#this file contains all global ansible variables for the playbooks
---
  operating_system:
    update_packages: true
    ping_nodes: true
  sync_gateway_version:
    build: couchbase-sync-gateway-enterprise_2.6.1_x86_64.rpm
    url: https://packages.couchbase.com/releases/couchbase-sync-gateway/2.6.1/couchbase-sync-gateway-enterprise_2.6.1_x86_64.rpm
    dest_dir: /tmp
    rpm_name: couchbase-sync-gateway

